image: "python:3.9"

stages:
    - test
    - build
    - deploy

build_package:
    stage: build
    script:
    - pip install pipenv
    - pipenv install
    - pipenv install pdoc3
    # Build not necessary for submodules
    # - pipenv run python setup.py bdist_wheel
    - pipenv run pdoc --html --output-dir public usgs
    artifacts:
        untracked: true
        paths:
        - public/usgs

Test-Pytest:
    stage: test
    script:
    - pip install pipenv
    - pipenv install
    - pipenv run pytest --junitxml=report.xml
    artifacts:
        when: always
        reports:
            junit: report.xml
        expire_in: 2 weeks

pages:
    image: alpine:latest
    stage: deploy
    script:
        - echo 'Nothing to do...'
    dependencies:
        - build_package
    artifacts:
        paths:
        - public/usgs
